### ISSUE TITLE
Question about XDRPC

### ISSUE THREAD

**Issue by ClementDreptin** [Unbrick/XboxController#1]
Hi,

My question is not something directly related to this project but I was looking for an open-source XDRPC implementation and I found one here. I'm trying to make my own in C but I'm struggling to understand how the protocol works, how to create the call data and how to get return values when calling functions. I've done a little bit of reverse engineering on the `xdrpc.dll` file provided in the XDK to check how Microsoft implemented it but I still fail to understand how it works under the hood.
I know you haven't touched this project in quite a bit of time but I would very much appreciate a little chat to discuss how your implementation works and possibly help me make mine.

Thanks in advance,

Cheers

**Comment by Unbrick** [comment]
Hi there,

To be fully honest, all the work I did was based on network interceptions. I just basically used numerous tools (and also the DLL directly) to issue method calls, recorded them and tried to make sense of them. The method calling is basically all implemented in the [RPCCallByAddressThread](https://github.com/Unbrick/XboxController/blob/master/app/src/main/java/com/unbrick/xbox/XBDM/threads/rpc/RPCCallByAddressThread.java) or the [RPCCallByOrdinalThread](https://github.com/Unbrick/XboxController/blob/master/app/src/main/java/com/unbrick/xbox/XBDM/threads/rpc/RPCCallByOrdinalThread.java).  

The most interesting for you might be the [construct_package_2()](https://github.com/Unbrick/XboxController/blob/master/app/src/main/java/com/unbrick/xbox/XBDM/threads/rpc/RPCCallByOrdinalThread.java#L65) methods, these should roughly outline how to craft a message for calling up a method. They also include examples of the recorded network traffic.

If you have any specific questions, feel free to ask, I hope I can answer at least a few of them!

Quick edit: Try looking into the XDRPC.dll using a tool like dnSpy, it should decompile pretty good. As far as i know the class XDRPCExecutionState should be responsible for packing / unpacking / invoking the remote calls.

**Comment by ClementDreptin** [comment]
Hi,

Sorry for the very late answer. I had already looked at your RPCCallByOrdinalThread class and decompiled `xdrpc.dll`, I just used dotPeek from JetBrains instead which also does a fantastic job. I tried to intercept the packets on my local network, as you suggested, but I caught COVID so trying to write an XDRPC implementation wasn't my first priority, as you can imagine...

Sorry again for the late answer and thanks for your advice, I'll get back at it once I feel better. I'll definitely get back to you if I get stuck on something.

**Comment by ClementDreptin** [comment]
Hi again,

It took me quite a while to finish my C implementation but it's now finished, it's far from perfect and doesn't support a lot of different argument and return value types but it does the job for the project it's in.
If you're interested, you can find it in my [ModuleLoader project](https://github.com/ClementDreptin/ModuleLoader) and more specifically in [`XDRPC.c`](https://github.com/ClementDreptin/ModuleLoader/blob/master/src/XDRPC.c).

Thanks again for your help, I would have never been able to finish my project without it! I can now close this issue.

**Comment by Unbrick** [comment]
Awsome work, will definitely check it out when i got time! Glad i could help!
